services:
  db:
    image: postgres:15-alpine
    container_name: quackpackage_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - quack-net

  master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quackpackage_master
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - RABBITMQ_EXCHANGE=${RABBITMQ_EXCHANGE}
      - CITY_ID=${CITY_ID}
      - USE_AMQP=true
      - AUTH0_ISSUER=${AUTH0_ISSUER:-https://frontendg15cityexpress.us.auth0.com/}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE:-https://api.andresitowan.com}
      - AUTH0_ROLES_CLAIM=${AUTH0_ROLES_CLAIM:-https://cityexpress/roles}
    depends_on:
      - db
    networks:
      - quack-net

  connector:
    build:
      context: ./connector
      dockerfile: Dockerfile
    container_name: quackpackage_connector
    restart: always
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - MASTER_API_URL=${MASTER_API_URL}
    depends_on:
      - master
    networks:
      - quack-net

  # --------------------------------------------------------
  # NUEVO MICROSERVICIO DE JOBS (BULLMQ + DIJKSTRA)
  # --------------------------------------------------------
  redis-jobs:
    image: redis:7-alpine
    container_name: quackpackage_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - quack-net

  job-master:
    build:
      context: ./jobs-service
      dockerfile: Dockerfile
    container_name: quackpackage_job_master
    restart: always
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis-jobs
      - REDIS_PORT=6379
      - PORT=3001
    depends_on:
      - redis-jobs
    networks:
      - quack-net
    command: npm run start:master # Sobrescribe el comando para correr el API

  job-worker:
    build:
      context: ./jobs-service
      dockerfile: Dockerfile
    container_name: quackpackage_job_worker
    restart: always
    environment:
      - REDIS_HOST=redis-jobs
      - REDIS_PORT=6379
    depends_on:
      - redis-jobs
    networks:
      - quack-net
    command: npm run start:worker # Sobrescribe el comando para correr el Worker

volumes:
  pgdata:

networks:
  quack-net:
    driver: bridge